### ISSUE TITLE
Becoming stable

### ISSUE THREAD

**Issue by MrCyjaneK** [MrCyjaneK/monero_c#12]
monero_c started as a rewrite to be used in only one wallet, but times have changed and now monero_c is also being used in xmruw, cake and stack, and with large amount of users and widespread adoption comes great responsibility, for this reason monero_c is becoming stable. What does that mean? Mostly turning branch protections on, all changes will come in separate PRs and adding other wallets into the CI to ensure compatibility across new revisions and to speed up testing of changes

# TODO

- [ ] Rebase against v0.18.3.4 tag (once released)
- [ ] Add cake into the CI
- [ ] Cleanup patches (just a little bit)
- [ ] Create upstream version of monero_c (one without custom patches)
- [ ] merge monero.dart into monero_c repo
- [ ] throw errors when wrong wrapper is being used (embed git hash at build time)
- [ ] you tell me
